axon:
  axonserver:
    servers: ${vcap.services.AxonServer.credentials.uri:localhost}

spring:
  datasource:
    url: jdbc:h2:./database;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    product: debug