POST http://127.0.0.1:1010/customers
Content-Type: application/json

{
  "firstName": "Dong-Gil",
  "lastName": "Nam",
  "email": "ndgndg91@gmail.com",
  "accountNumber":"12345",

  "creditCardNumber":"5388032306460084",
  "creditCardType":"MASTERCARD",

  "street1": "235, Toegye-ro, Jung-gu, Seoul, Republic of Korea",
  "street2": "B-804",
  "state": "SEOUL",
  "city": "SEOUL",
  "country":"KOREA",
  "zipCode":"04558",
  "addressType":"SHIPPING"
}
> {%
client.global.set("id", response.headers.valueOf("Location").split("/")[2]);
  %}
###

GET http://127.0.0.1:1010/customers/{{id}}